#!/usr/bin/env python3
"""
SoterCare Data Recorder — data_recorder.py
Continuously listens to the Redis stream (sotercare_history) generated by
gateway_master.py and saves all incoming data as JSON Lines (.jsonl).

Run this script alongside the gateway master to capture all raw sensor data,
AI inferences, and fall alerts.
"""

import os
import json
import time
from datetime import datetime
import redis

# ── Configuration ─────────────────────────────────────────────────────────────
REDIS_HOST = "localhost"
REDIS_PORT = 6379
REDIS_STREAM = "sotercare_history"
RECORDINGS_DIR = os.path.join(os.path.dirname(__file__), "recordings")

# Create recordings directory if it doesn't exist
os.makedirs(RECORDINGS_DIR, exist_ok=True)


def main():
    # Generate timestamped filename
    timestamp_str = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"sotercare_recording_{timestamp_str}.jsonl"
    filepath = os.path.join(RECORDINGS_DIR, filename)

    print("=" * 60)
    print(" SoterCare Data Recorder — Starting")
    print("=" * 60)
    print(f"[STATUS] Connecting to Redis on {REDIS_HOST}:{REDIS_PORT}...")

    # Connect to Redis
    try:
        r = redis.Redis(host=REDIS_HOST, port=REDIS_PORT, decode_responses=True)
        r.ping()
        print("[STATUS] Connected to Redis successfully.")
    except Exception as e:
        print(f"[ERROR] Could not connect to Redis: {e}")
        print("Please ensure the Redis server is running.")
        return

    print(f"\n[RECORDING] Writing data to:")
    print(f"  --> {filepath}")
    print("\n[INFO] Press Ctrl+C to gracefully stop recording.\n")

    # Start reading from the END of the stream ($)
    # This ensures we only capture new data generated while this script runs
    last_id = "$"
    records_saved = 0
    start_time = time.time()

    try:
        # Open file in append mode (unbuffered/line-buffered by default in Python 3 text mode)
        with open(filepath, "a", encoding="utf-8") as f:
            while True:
                # Block for up to 1 second waiting for new data
                response = r.xread({REDIS_STREAM: last_id}, count=100, block=1000)

                if response:
                    stream_name, messages = response[0]
                    for msg_id, data in messages:
                        # Append the JSON string + newline
                        f.write(json.dumps(data) + "\n")
                        
                        # Update the last read ID
                        last_id = msg_id
                        records_saved += 1

                # Periodically print status every 5 seconds
                elapsed = time.time() - start_time
                if int(elapsed) % 5 == 0 and int(elapsed) > 0 and records_saved > 0:
                    hz = records_saved / elapsed
                    print(f"\r[STATUS] Saved {records_saved} records (~{hz:.1f}Hz) ...", end="", flush=True)

    except KeyboardInterrupt:
        print(f"\n\n[MAIN] Stop command received (Ctrl+C).")
        print(f"[SUMMARY] Successfully saved {records_saved} records to {filename}.")
        print("[MAIN] Shutting down.")
    except Exception as e:
        print(f"\n[ERROR] An unexpected error occurred: {e}")

if __name__ == "__main__":
    main()
